# Deployment do postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "Gio@123#"
          - name: POSTGRES_USER
            value: "giozandonai"
          - name: POSTGRES_DB
            value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
---
# Deployment da Aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: kubenews
          image: giozandonai/kube-news:latest
          env:
          - name: DB_PASSWORD
            value: "Gio@123#"
          - name: DB_USERNAME
            value: "giozandonai"
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_HOST
            value: "postgre" # nome do serviço do postgre

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
